/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    showcases: Showcase;
    'user-behavior-events': UserBehaviorEvent;
    'user-sessions': UserSession;
    'page-views': PageView;
    'heatmap-data': HeatmapDatum;
    'project-views': ProjectView;
    'conversion-funnels': ConversionFunnel;
    'contact-inquiries': ContactInquiry;
    'newsletter-subscribers': NewsletterSubscriber;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    showcases: ShowcasesSelect<false> | ShowcasesSelect<true>;
    'user-behavior-events': UserBehaviorEventsSelect<false> | UserBehaviorEventsSelect<true>;
    'user-sessions': UserSessionsSelect<false> | UserSessionsSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    'heatmap-data': HeatmapDataSelect<false> | HeatmapDataSelect<true>;
    'project-views': ProjectViewsSelect<false> | ProjectViewsSelect<true>;
    'conversion-funnels': ConversionFunnelsSelect<false> | ConversionFunnelsSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (string | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (string | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (string | null) | User;
  customerEmail?: string | null;
  transactions?: (string | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: string | Media;
        variantOption?: (string | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (string | VariantType)[] | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  relatedProducts?: (string | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  categories?: (string | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: string;
  _variantOptions_options_order?: string | null;
  variantType: string | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: string;
  label: string;
  name: string;
  options?: {
    docs?: (string | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (string | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: string | Product;
  options: (string | VariantOption)[];
  inventory?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (string | null) | User;
  customerEmail?: string | null;
  order?: (string | null) | Order;
  cart?: (string | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (string | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer?: (string | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcases".
 */
export interface Showcase {
  id: string;
  title: string;
  client: string;
  tagline: string;
  year: string;
  category: 'E-commerce' | 'FinTech' | 'Healthcare' | 'AI/ML' | 'Blockchain' | 'IoT' | 'SaaS' | 'Social';
  status: 'completed' | 'in-progress' | 'maintenance' | 'deprecated';
  description: {
    overview: string;
    challenge: string;
    solution: string;
    impact: string;
  };
  thumbnail: string | Media;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  techStack?:
    | {
        name: string;
        /**
         * Lucide icon name (e.g., Cpu, Zap, Box)
         */
        icon: string;
        category: 'frontend' | 'backend' | 'devops' | 'mobile' | 'cloud' | 'core';
        version?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  team?:
    | {
        name: string;
        role: string;
        /**
         * URL or path to avatar
         */
        avatar?: string | null;
        contribution?: string | null;
        id?: string | null;
      }[]
    | null;
  milestones?:
    | {
        date: string;
        title: string;
        description?: string | null;
        completed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  stats: {
    commits: number;
    hoursSpent: number;
    performanceScore: number;
    uptime?: string | null;
    users?: string | null;
  };
  links?: {
    live?: string | null;
    github?: string | null;
    caseStudy?: string | null;
  };
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  techDetails?: {
    architecture?: string | null;
    language?: string | null;
    database?: string | null;
    hosting?: string | null;
  };
  testimonial?: {
    quote?: string | null;
    author?: string | null;
    role?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  theme: {
    /**
     * Hex color (e.g., #8B5CF6)
     */
    primary: string;
    /**
     * Hex color
     */
    secondary?: string | null;
    /**
     * Hex color
     */
    accent?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks all user interactions and behavior events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-behavior-events".
 */
export interface UserBehaviorEvent {
  id: string;
  /**
   * Links to user session for grouping events
   */
  sessionId: string;
  eventType:
    | 'click'
    | 'hover'
    | 'scroll'
    | 'focus'
    | 'blur'
    | 'submit'
    | 'navigation'
    | 'page_load'
    | 'page_exit'
    | 'video_play'
    | 'video_pause'
    | 'download'
    | 'error';
  eventCategory: 'button' | 'link' | 'form' | 'project' | 'navigation' | 'media' | 'cta' | 'social' | 'other';
  /**
   * HTML element ID or unique identifier
   */
  elementId?: string | null;
  /**
   * Text content of the interacted element
   */
  elementText?: string | null;
  /**
   * X/Y coordinates of the element or click position
   */
  elementPosition?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current page URL where event occurred
   */
  pageUrl: string;
  /**
   * Previous page URL
   */
  referrerUrl?: string | null;
  timestamp: string;
  /**
   * Time in milliseconds user spent on page before this action
   */
  decisionTime?: number | null;
  /**
   * Time in milliseconds user hovered before clicking
   */
  hoverDuration?: number | null;
  /**
   * Percentage of page scrolled (0-100)
   */
  scrollDepth?: number | null;
  /**
   * Window dimensions {width, height}
   */
  viewportSize?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Flexible JSON field for additional context
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks complete user sessions from entry to exit
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-sessions".
 */
export interface UserSession {
  id: string;
  /**
   * Unique session identifier (UUID)
   */
  sessionId: string;
  /**
   * Linked user if logged in
   */
  userId?: (string | null) | User;
  /**
   * Full user agent string
   */
  userAgent?: string | null;
  /**
   * User IP address (consider privacy implications)
   */
  ipAddress?: string | null;
  deviceType?: ('desktop' | 'mobile' | 'tablet' | 'unknown') | null;
  browserName?: string | null;
  browserVersion?: string | null;
  /**
   * Operating system
   */
  os?: string | null;
  /**
   * Screen dimensions {width, height}
   */
  screenResolution?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Browser language preference
   */
  language?: string | null;
  /**
   * User timezone
   */
  timezone?: string | null;
  /**
   * First page visited in session
   */
  entryPage: string;
  /**
   * Last page visited before session ended
   */
  exitPage?: string | null;
  /**
   * UTM source, referrer domain, or direct
   */
  landingSource?: string | null;
  utmParams?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
  };
  sessionStart: string;
  sessionEnd?: string | null;
  /**
   * Total session duration in seconds
   */
  sessionDuration?: number | null;
  /**
   * Total number of pages viewed
   */
  pageViews?: number | null;
  /**
   * User left after viewing only one page
   */
  bounced?: boolean | null;
  /**
   * User completed a desired action (form, newsletter, etc.)
   */
  converted?: boolean | null;
  /**
   * Type of conversion if converted
   */
  conversionType?: ('contact_form' | 'newsletter' | 'project_inquiry' | 'download' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual page view tracking with performance metrics
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: string;
  /**
   * Links to user session
   */
  sessionId: string;
  /**
   * Full URL of the page
   */
  pageUrl: string;
  /**
   * Page title from document.title
   */
  pageTitle?: string | null;
  timestamp: string;
  /**
   * Duration spent on page in seconds
   */
  timeOnPage?: number | null;
  /**
   * Maximum scroll percentage reached (0-100)
   */
  scrollDepth?: number | null;
  /**
   * Whether this was the exit page for the session
   */
  exitPage?: boolean | null;
  performanceMetrics?: {
    /**
     * Page load time in milliseconds
     */
    loadTime?: number | null;
    /**
     * Time to interactive (TTI) in milliseconds
     */
    timeToInteractive?: number | null;
    /**
     * LCP metric in milliseconds
     */
    largestContentfulPaint?: number | null;
    /**
     * FID metric in milliseconds
     */
    firstInputDelay?: number | null;
    /**
     * CLS metric (score)
     */
    cumulativeLayoutShift?: number | null;
  };
  /**
   * Referrer URL within the site
   */
  previousPage?: string | null;
  /**
   * Next page visited (if any)
   */
  nextPage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aggregated click and scroll heatmap data for visualization
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heatmap-data".
 */
export interface HeatmapDatum {
  id: string;
  /**
   * Page identifier for heatmap
   */
  pageUrl: string;
  /**
   * CSS selector for the element
   */
  elementSelector?: string | null;
  elementType?: ('button' | 'link' | 'image' | 'text' | 'form_field' | 'other') | null;
  /**
   * Total number of clicks on this element
   */
  clickCount?: number | null;
  /**
   * Total number of hovers
   */
  hoverCount?: number | null;
  /**
   * Average hover time in milliseconds
   */
  averageHoverDuration?: number | null;
  /**
   * Date for time-series analysis (aggregated by day)
   */
  date: string;
  /**
   * Click counts by device type
   */
  deviceBreakdown?: {
    desktop?: number | null;
    mobile?: number | null;
    tablet?: number | null;
  };
  /**
   * Individual click coordinates for heatmap visualization
   */
  clickPositions?:
    | {
        x: number;
        y: number;
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Distribution of scroll depths for this page
   */
  scrollDepthDistribution?: {
    /**
     * Users who scrolled 0-25%
     */
    depth_0_25?: number | null;
    /**
     * Users who scrolled 25-50%
     */
    depth_25_50?: number | null;
    /**
     * Users who scrolled 50-75%
     */
    depth_50_75?: number | null;
    /**
     * Users who scrolled 75-100%
     */
    depth_75_100?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Specific tracking for project showcase interactions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-views".
 */
export interface ProjectView {
  id: string;
  /**
   * Links to user session
   */
  sessionId: string;
  /**
   * Link to the actual project if available in CMS
   */
  project?: (string | null) | Showcase;
  /**
   * Project identifier (for projects not in CMS)
   */
  projectId: string;
  /**
   * Project title (denormalized for quick access)
   */
  projectTitle: string;
  projectCategory?:
    | ('E-commerce' | 'FinTech' | 'Healthcare' | 'AI/ML' | 'Blockchain' | 'IoT' | 'SaaS' | 'Social')
    | null;
  viewTimestamp: string;
  /**
   * Time spent viewing project in seconds
   */
  viewDuration?: number | null;
  interactionType?:
    | ('homepage_click' | 'direct_link' | 'category_filter' | 'search_result' | 'related_project' | 'archive_browse')
    | null;
  /**
   * Which sections of the project were viewed
   */
  sectionsViewed?:
    | {
        section:
          | 'overview'
          | 'challenge'
          | 'solution'
          | 'impact'
          | 'tech_stack'
          | 'team'
          | 'milestones'
          | 'gallery'
          | 'testimonial';
        /**
         * Time spent in this section (seconds)
         */
        timeSpent?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Whether user clicked any call-to-action
   */
  ctaClicked?: boolean | null;
  /**
   * Which CTA was clicked
   */
  ctaType?: ('live_link' | 'github' | 'case_study' | 'contact' | 'download') | null;
  /**
   * Previous project viewed (if any)
   */
  previousProject?: string | null;
  /**
   * Next project viewed (if any)
   */
  nextProject?: string | null;
  /**
   * Which technologies user clicked for more info
   */
  techStackClicked?:
    | {
        technology?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Track conversion funnel steps and drop-off rates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversion-funnels".
 */
export interface ConversionFunnel {
  id: string;
  funnelName:
    | 'contact_form'
    | 'project_to_inquiry'
    | 'newsletter_signup'
    | 'homepage_to_contact'
    | 'archive_to_inquiry'
    | 'blog_to_newsletter';
  /**
   * Links to user session
   */
  sessionId: string;
  steps?:
    | {
        stepName: string;
        /**
         * URL or page identifier for this step
         */
        stepUrl?: string | null;
        stepOrder: number;
        /**
         * What user needs to do at this step
         */
        requiredAction?: string | null;
        completed?: boolean | null;
        completedAt?: string | null;
        /**
         * Time spent on this step in seconds
         */
        timeSpent?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Current step number (where user is in funnel)
   */
  currentStep: number;
  /**
   * Whether the entire funnel was completed
   */
  completed?: boolean | null;
  /**
   * Step number where user abandoned the funnel
   */
  droppedOffAt?: number | null;
  startedAt: string;
  completedAt?: string | null;
  /**
   * Total time to complete funnel in seconds
   */
  totalDuration?: number | null;
  /**
   * How user entered this funnel
   */
  entrySource?: string | null;
  /**
   * Reason for abandoning the funnel
   */
  dropoffReason?: ('navigation_away' | 'timeout' | 'form_error' | 'load_issue' | 'unknown') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions with tracking context
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: string;
  /**
   * Links to user session
   */
  sessionId?: string | null;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  projectType:
    | 'ecommerce'
    | 'ai_ml'
    | 'blockchain'
    | 'custom_app'
    | 'mobile'
    | 'design'
    | 'consulting'
    | 'maintenance'
    | 'other';
  budget?: ('under_10k' | '10k_50k' | '50k_100k' | '100k_250k' | 'over_250k' | 'not_sure') | null;
  timeline?: ('urgent' | '1_3_months' | '3_6_months' | '6_plus_months' | 'flexible') | null;
  message: string;
  submittedAt: string;
  /**
   * Lead status in the sales pipeline
   */
  status: 'new' | 'contacted' | 'qualified' | 'proposal_sent' | 'negotiating' | 'converted' | 'rejected' | 'spam';
  /**
   * Page where they submitted the form
   */
  source?: string | null;
  /**
   * If contacted from a specific project page
   */
  referringProject?: (string | null) | Showcase;
  /**
   * Time spent filling out the form in seconds
   */
  formInteractionTime?: number | null;
  /**
   * For spam prevention and rate limiting
   */
  ipAddress?: string | null;
  /**
   * Internal notes about this inquiry
   */
  notes?: string | null;
  /**
   * Sales rep or team member assigned to this lead
   */
  assignedTo?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter subscription management with preferences
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: string;
  email: string;
  name?: string | null;
  subscribedAt: string;
  status: 'pending' | 'active' | 'unsubscribed' | 'bounced' | 'complained';
  /**
   * Where they subscribed from
   */
  source?:
    | ('homepage_footer' | 'blog' | 'project_page' | 'popup' | 'contact_form' | 'landing_page' | 'manual_import')
    | null;
  /**
   * Subscriber segments for targeted campaigns
   */
  tags?:
    | {
        tag?: ('client' | 'prospect' | 'partner' | 'developer' | 'designer' | 'entrepreneur' | 'student') | null;
        id?: string | null;
      }[]
    | null;
  preferences?: {
    frequency?: ('daily' | 'weekly' | 'biweekly' | 'monthly' | 'major_updates') | null;
    interests?:
      | {
          interest?:
            | (
                | 'web_dev'
                | 'ai_ml'
                | 'blockchain'
                | 'ecommerce'
                | 'design'
                | 'mobile'
                | 'devops'
                | 'case_studies'
                | 'news'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    language?: ('pl' | 'en') | null;
  };
  /**
   * When they unsubscribed
   */
  unsubscribedAt?: string | null;
  unsubscribeReason?: ('too_frequent' | 'not_relevant' | 'never_subscribed' | 'other') | null;
  /**
   * Email confirmation verified
   */
  doubleOptInConfirmed?: boolean | null;
  confirmationSentAt?: string | null;
  /**
   * Unique token for email confirmation
   */
  confirmationToken?: string | null;
  /**
   * Last newsletter sent to this subscriber
   */
  lastEmailSent?: string | null;
  /**
   * Total emails sent to this subscriber
   */
  emailsSent?: number | null;
  /**
   * Total emails opened
   */
  emailsOpened?: number | null;
  /**
   * Total links clicked in emails
   */
  linksClicked?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'showcases';
        value: string | Showcase;
      } | null)
    | ({
        relationTo: 'user-behavior-events';
        value: string | UserBehaviorEvent;
      } | null)
    | ({
        relationTo: 'user-sessions';
        value: string | UserSession;
      } | null)
    | ({
        relationTo: 'page-views';
        value: string | PageView;
      } | null)
    | ({
        relationTo: 'heatmap-data';
        value: string | HeatmapDatum;
      } | null)
    | ({
        relationTo: 'project-views';
        value: string | ProjectView;
      } | null)
    | ({
        relationTo: 'conversion-funnels';
        value: string | ConversionFunnel;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: string | ContactInquiry;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: string | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcases_select".
 */
export interface ShowcasesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  tagline?: T;
  year?: T;
  category?: T;
  status?: T;
  description?:
    | T
    | {
        overview?: T;
        challenge?: T;
        solution?: T;
        impact?: T;
      };
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        name?: T;
        icon?: T;
        category?: T;
        version?: T;
        description?: T;
        id?: T;
      };
  team?:
    | T
    | {
        name?: T;
        role?: T;
        avatar?: T;
        contribution?: T;
        id?: T;
      };
  milestones?:
    | T
    | {
        date?: T;
        title?: T;
        description?: T;
        completed?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        commits?: T;
        hoursSpent?: T;
        performanceScore?: T;
        uptime?: T;
        users?: T;
      };
  links?:
    | T
    | {
        live?: T;
        github?: T;
        caseStudy?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  techDetails?:
    | T
    | {
        architecture?: T;
        language?: T;
        database?: T;
        hosting?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  theme?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-behavior-events_select".
 */
export interface UserBehaviorEventsSelect<T extends boolean = true> {
  sessionId?: T;
  eventType?: T;
  eventCategory?: T;
  elementId?: T;
  elementText?: T;
  elementPosition?: T;
  pageUrl?: T;
  referrerUrl?: T;
  timestamp?: T;
  decisionTime?: T;
  hoverDuration?: T;
  scrollDepth?: T;
  viewportSize?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-sessions_select".
 */
export interface UserSessionsSelect<T extends boolean = true> {
  sessionId?: T;
  userId?: T;
  userAgent?: T;
  ipAddress?: T;
  deviceType?: T;
  browserName?: T;
  browserVersion?: T;
  os?: T;
  screenResolution?: T;
  language?: T;
  timezone?: T;
  entryPage?: T;
  exitPage?: T;
  landingSource?: T;
  utmParams?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
      };
  sessionStart?: T;
  sessionEnd?: T;
  sessionDuration?: T;
  pageViews?: T;
  bounced?: T;
  converted?: T;
  conversionType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  sessionId?: T;
  pageUrl?: T;
  pageTitle?: T;
  timestamp?: T;
  timeOnPage?: T;
  scrollDepth?: T;
  exitPage?: T;
  performanceMetrics?:
    | T
    | {
        loadTime?: T;
        timeToInteractive?: T;
        largestContentfulPaint?: T;
        firstInputDelay?: T;
        cumulativeLayoutShift?: T;
      };
  previousPage?: T;
  nextPage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heatmap-data_select".
 */
export interface HeatmapDataSelect<T extends boolean = true> {
  pageUrl?: T;
  elementSelector?: T;
  elementType?: T;
  clickCount?: T;
  hoverCount?: T;
  averageHoverDuration?: T;
  date?: T;
  deviceBreakdown?:
    | T
    | {
        desktop?: T;
        mobile?: T;
        tablet?: T;
      };
  clickPositions?:
    | T
    | {
        x?: T;
        y?: T;
        timestamp?: T;
        id?: T;
      };
  scrollDepthDistribution?:
    | T
    | {
        depth_0_25?: T;
        depth_25_50?: T;
        depth_50_75?: T;
        depth_75_100?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-views_select".
 */
export interface ProjectViewsSelect<T extends boolean = true> {
  sessionId?: T;
  project?: T;
  projectId?: T;
  projectTitle?: T;
  projectCategory?: T;
  viewTimestamp?: T;
  viewDuration?: T;
  interactionType?: T;
  sectionsViewed?:
    | T
    | {
        section?: T;
        timeSpent?: T;
        id?: T;
      };
  ctaClicked?: T;
  ctaType?: T;
  previousProject?: T;
  nextProject?: T;
  techStackClicked?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversion-funnels_select".
 */
export interface ConversionFunnelsSelect<T extends boolean = true> {
  funnelName?: T;
  sessionId?: T;
  steps?:
    | T
    | {
        stepName?: T;
        stepUrl?: T;
        stepOrder?: T;
        requiredAction?: T;
        completed?: T;
        completedAt?: T;
        timeSpent?: T;
        id?: T;
      };
  currentStep?: T;
  completed?: T;
  droppedOffAt?: T;
  startedAt?: T;
  completedAt?: T;
  totalDuration?: T;
  entrySource?: T;
  dropoffReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  sessionId?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  projectType?: T;
  budget?: T;
  timeline?: T;
  message?: T;
  submittedAt?: T;
  status?: T;
  source?: T;
  referringProject?: T;
  formInteractionTime?: T;
  ipAddress?: T;
  notes?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  subscribedAt?: T;
  status?: T;
  source?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  preferences?:
    | T
    | {
        frequency?: T;
        interests?:
          | T
          | {
              interest?: T;
              id?: T;
            };
        language?: T;
      };
  unsubscribedAt?: T;
  unsubscribeReason?: T;
  doubleOptInConfirmed?: T;
  confirmationSentAt?: T;
  confirmationToken?: T;
  lastEmailSent?: T;
  emailsSent?: T;
  emailsOpened?: T;
  linksClicked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}